name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Debug Zerostep configuration
      run: |
        echo "Zerostep version:"
        npm list @zerostep/playwright
        echo "Zerostep configuration:"
        cat zerostep.json || echo "zerostep.json not found"
    - name: Run Playwright tests with debug output
      run: DEBUG=pw:api npm run test
    - name: Install Allure command line
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        curl -o allure-2.13.8.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.tgz
        sudo tar -zxvf allure-2.13.8.tgz -C /opt/
        sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure
    - name: Generate Allure Report
      run: allure generate allure-results -o allure-report --clean
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-debug-logs
        path: test-results/
        retention-days: 5